package brillant.soft.controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import java.net.URL;
import java.time.LocalDate;
import java.util.ResourceBundle;

import brillant.soft.util.DateUtil;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class ItemController implements Initializable {
	@FXML
	private HBox itemC;
	@FXML
	private Label date;
	@FXML
	private Label caisse;
	@FXML
	private Label carteBancaire;
	@FXML
	private Label orangeMoney;
	@FXML
	private Label total;
	@FXML
	private Label depense;
	@FXML
	private Label solde;
	@FXML
	private Button action;

	// Event Listener on Button[#action].onAction
	@FXML
	public void handleActionClick(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		initialiseItem();
		
	}
	
	public void initialiseItem() {
		//itemC.setVisible(false);
	}
	
	public void setValue(float caisse, float cb, float om, float total, float depense, float solde, LocalDate date){
		
		this.caisse.setText(String.valueOf(caisse));
		this.carteBancaire.setText(String.valueOf(cb));
		this.orangeMoney.setText(String.valueOf(om));
		this.total.setText(String.valueOf(total));
		this.depense.setText(String.valueOf(depense));
		this.solde.setText(String.valueOf(solde));
		this.date.setText(DateUtil.format(date));
		
	}
}
